# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbf44a9f32225ead53f3e85e026db3bfa814865e63b275f19172047fc1e4616d4f4bd2a5c60af5e66d7eba1cf0a74558daab8b20cd2d5a4ebd68df1525151e39

test:
  secret_key_base: d3cee408f4f57c1fe7f51ef6db45151fa2e09b64d42d1a90083203ec67c27dbf3b629bff6f4a99a0be222568996d1d1778ec35d4cdc8b827cd5e758e4290c236

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
